
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import dynamic from 'next/dynamic';
const { AppSidebar } = dynamic(() => import('@/components/app-sidebar'), { ssr: false });
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import Authprovider from "@/utils/Authprovider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <SidebarProvider>
      <AppSidebar />
      <main>
        <Authprovider>
      <ModeToggle/>
        <SidebarTrigger />
        
        {children}
        </Authprovider>
      </main>
    </SidebarProvider>
   
    </ThemeProvider> 
      </body>
    </html>
  );
}
